blogs/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('',views.index,name='starting_page'),
    path('posts',views.posts,name='post_page'),
    path('post/<slug:slug>',views.single_post,name='post_detail'),
    path('K',views.Karbaran_list),
    path('P/', views.Product_list, name='product-list'),
    path('P/<slug:slug>', views.product_detail, name='product-detail'),

]

contactus_module/urls.py
from django.urls import path

from . import views

app_name = 'contactus_module'

urlpatterns = [
    path('', views.contactus_func, name='contactus_func'),
    path('register/',views.user_register, name='user-register'),
    path('login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user-logout')
]

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home_module'

urlpatterns = [
    path('',views.home_func,name='home'),
]

website/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include



urlpatterns = [
    path('',lambda request: redirect('/blog/P')),
    path('admin/', admin.site.urls),
    path('blog/',include('blogs.urls')),
    path('contactus/',include('contactus_module.urls',namespace='contactus_module')),
    path('home/',include('home_module.urls',namespace='home_module')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}
        page_ .....
    {% endblock %}
    </title>

     {% block header_reference %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'app.css' %}">


</head>
<body>
    <header id="main-navigation">
    <h1> <a href="{% url 'starting_page' %}">My Site</a></h1>
    <nav>
        <a href="{% url 'post_page' %}">All Post</a>
    </nav>
    </header>



    {% block page_content %}
        Welcom to Django
    {% endblock %}

    {% block footer_reference %}
    {% endblock %}
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
            {% block page_title %}

            {% endblock %}

    </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block header_reference %}

    {% endblock %}
</head>
<body>
    {% block page_content %}

        my web

    {% endblock %}
    {% block footer_reference %}

    {% endblock %}

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home_module:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contactus_module:user-register' %}">register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contactus_module:user-login' %}}">login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contactus_module:user-logout' %}}">logout</a>
        </li>

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>